repos:
  - repo: https://github.com/MarketSquare/robotframework-tidy
    rev: 4.13.0
    hooks:
      - id: robotidy
        name: Robotidy

  - repo: https://github.com/MarketSquare/robotframework-robocop
    rev: 5.3.0
    hooks:
      - id: robocop
        name: Robocop
