[tool.robotidy]
diff = true
overwrite = false
verbose = true
separator = "space"
spacecount = 2
indent = 4
line_length = 120
lineseparator = "native"
configure = [
    "AlignKeywordsSection:alignment_type=auto",
    "AlignSettingsSection",
    "AlignTemplatedTestCases",
    "AlignTestCasesSection",
    "AlignVariablesSection:enabled=True",
    "DiscardEmptySections:enabled=False",
    "NormalizeNewLines:section_lines=1:test_case_lines=1:keyword_lines=1"
]

[tool.robocop]
exclude = [
    "missing-doc-keyword",
    "missing-doc-test-case",
    "missing-doc-resource-file",
    "missing-trailing-blank-line"
]
configure = [
    "wrong-case-in-keyword-name:convention:first_word_capitalized",
    "too-many-calls-in-keyword:max_calls:20",
    "file-too-long:max_lines:500",
    "too-many-arguments:max_args:10"
]